[build-system]
requires = ["setuptools>=61", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "qrid_thesis_toolkit"
version = "0.1.0"
description = "Toolkit for my thesis experiments"
dependencies = [
    "torch>=2.6.0",
    "torchvision>=0.21.0",
    "onnx>=1.17.0",
    "onnxruntime>=1.21.0",
    "numpy>=2.1.1",
    "opencv-python>=4.11.0.86",
    "pyyaml>=6.0.2",
    "matplotlib>=3.10.1",
    "pandas>=2.2.3",
    "tqdm>=4.67.1",
    "ultralytics>=8.3.109",
    "albumentations>=2.0.5",
    "pycocotools>=2.0.8",
    "seaborn>=0.13.2",
    "scipy>=1.15.2"
]

[project.optional-dependencies]
dev = [
    "jupyterlab",
    "ipykernel",
    "notebook"
]

[tool.setuptools.packages.find]
where    = ["."]
include  = ["functions*", "helpers*"]         # grab functions and its sub-packages
exclude  = ["notebooks*", "models*", "thesis*"]
namespaces = false